### ISSUE TITLE
I don't know how to set this op on a Windows 10 PC can you guide me 

### ISSUE THREAD

**Issue by Lawyer447** [Puyodead1/udemy-downloader#54]
I have Windows 10 64bit.

**Comment by Puyodead1** [comment]
- install python 3
- either install [git ](https://git-scm.com/download/win) and clone the repo (recommended since its way easier to get updates for the tool), or download the master branch zip file and extract it somewhere (easier for most people) 
- install the python dependencies with ``python install -r requirements.txt``
- download [ffmpeg](https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-essentials.7z), [aria2c](https://github.com/aria2/aria2/releases/latest), and the [bento4 sdk](https://www.bento4.com/downloads/). 
- unzip them all somewhere like your c drive. 
- then [add them all to your system path](https://www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/)
- use [widevine-l3-guesser](https://github.com/Satsuoni/widevine-l3-guesser) or one of its forks to get key and key ids
- follow the [readme](https://github.com/Puyodead1/udemy-downloader#setting-up) from here on

**Comment by kiranfegade121** [comment]
Hi, 

I think no widevine extension works now to get keys. Please do let me know @Puyodead1, If you are still able to get keys, so that I try to find what is a wrong in my case. Does any extension works for you, chrome or firefox extension? 

Thanks in advance...

**Comment by Puyodead1** [comment]
An update to this for anyone who is looking for setup steps, the latest version now uses [shaka-packager](https://github.com/google/shaka-packager/releases/latest) instead of bento4. The widevine guesser extension is also no longer working on udemy, if you find a way to obtain keys, then you can still use this program for downloading.
